let yourName = prompt ('What is your name?')
let favoriteSport = prompt ('What is your favorite sport?')
let favoriteRelax = prompt ('What is your favorite thing to do to relax?')
confirm(`${yourName} your favorite sport is ${favoriteSport} and to relax you usually ${favoriteRelax}`)
console.log(`${yourName} your favorite sport is ${favoriteSport} and to relax you usually ${favoriteRelax}`)